### ISSUE TITLE
Move basic getting Started content into "pre-requisites" section 

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access_docs#40]
NCI account, Gadi resources, etc
Creat a separate "pre-requisites" section for this basic content (or put on welcome page of access docs)

**Comment by KAUR1984** [comment]
Hi @heidinett! Was just wondering if this issue is referring to the `getting started` tab in the `development` branch (please find the below screenshot): 

![Screenshot 2023-07-28 at 11 44 20 am](https://github.com/ACCESS-Hive/access_docs/assets/42607679/e6ac227a-c6e5-4f93-9742-f04abdc604a9)

**Comment by heidinett** [comment]
Yes @KAUR1984, it appears that this issue has already been resolved!
This issue can be closed.

**Comment by KAUR1984** [comment]
Awesome! Thanks.
